### ISSUE TITLE
Add flats providers.

### ISSUE THREAD

**Issue by cheshir** [cheshir/flats-finder#2]
Add several popular flats providers like dwell.

**Comment by LehaMotovilov** [comment]
Ok, I'll try to add Dwell.

**Comment by cheshir** [comment]
I've added [Dwell](https://github.com/cheshir/flats-finder/commit/2c6c3ca172e6beca78e2c07499ec4287c5b7ece5) and [Lun](https://github.com/cheshir/flats-finder/commit/a1f42cca277a75fa61e0e20f062641e7759fccb8).

**Comment by LehaMotovilov** [comment]
Thanks dude :)
